In [35]:
import numpy as np

In [69]:
def gen_density_map():
    density_scale = np.zeros((10, 10, 10))
    r, c, d = density_scale.shape
    for i in range(r):
        for j in range(c):
            for k in range(d):
                if i == 0 and j == 0 and k == 0:
                    density_scale[i, j, k] = 1
                else:
                    density_scale[i, j, k] = 1 / ((i**2 + j**2 + k**2) ** 0.5)  # 1/dist
    v_flip = np.flip(density_scale, axis=0)
    density_scale = np.concatenate((v_flip, density_scale[1:, :, :]), axis=0)
    h_flip = np.flip(density_scale, axis=1)
    density_scale = np.concatenate([h_flip, density_scale[:, 1:, :]], axis=1)
    d_flip = np.flip(density_scale, axis=2)
    density_scale = np.concatenate([d_flip, density_scale[:, :, 1:]], axis=2)
    return density_scale

In [70]:
density_scale = gen_density_map()
density_scale.shape

(19, 19, 19)

In [77]:
count = np.ones((3, 3, 3))
count[0, 0, 0] = 1
count[-1, -1, -1] = 1

In [78]:
density_map = np.zeros((3, 3, 3))
mid = density_scale.shape[0] // 2
print(mid)
r, c, d = density_map.shape
print(r, c, d)
for i in range(r):
    for j in range(c):
        for k in range(d):
            density_map[i, j, k] = np.sum(
                density_scale[mid - i : mid - i + 3, mid - j : mid - j + 3, mid - k : mid - k + 3]
                * count
            )

density_map

9
3 3 3


array([[[14.45603236, 16.02672924, 14.45603236],
        [16.02672924, 17.88810287, 16.02672924],
        [14.45603236, 16.02672924, 14.45603236]],

       [[16.02672924, 17.88810287, 16.02672924],
        [17.88810287, 20.10408353, 17.88810287],
        [16.02672924, 17.88810287, 16.02672924]],

       [[14.45603236, 16.02672924, 14.45603236],
        [16.02672924, 17.88810287, 16.02672924],
        [14.45603236, 16.02672924, 14.45603236]]])

In [79]:
b = np.arange(1000)

In [80]:
b = np.arange(1000).reshape(10, 10, 10)

In [81]:
b[:, 0, 0]

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [82]:
b[0, :, 0]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [83]:
b = np.arange(64).reshape(4, 4, 4)

In [84]:
b[:, :, 0]

array([[ 0,  4,  8, 12],
       [16, 20, 24, 28],
       [32, 36, 40, 44],
       [48, 52, 56, 60]])

In [85]:
b[:, 0, :]

array([[ 0,  1,  2,  3],
       [16, 17, 18, 19],
       [32, 33, 34, 35],
       [48, 49, 50, 51]])

In [86]:
b[0, :, :]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [87]:
c = b.reshape(2, 2, 2, 2, 2, 2)

In [88]:
summed_array = c.sum(axis=(1, 3, 5))
summed_array

array([[[ 84, 100],
        [148, 164]],

       [[340, 356],
        [404, 420]]])

In [89]:
c

array([[[[[[ 0,  1],
           [ 2,  3]],

          [[ 4,  5],
           [ 6,  7]]],


         [[[ 8,  9],
           [10, 11]],

          [[12, 13],
           [14, 15]]]],



        [[[[16, 17],
           [18, 19]],

          [[20, 21],
           [22, 23]]],


         [[[24, 25],
           [26, 27]],

          [[28, 29],
           [30, 31]]]]],




       [[[[[32, 33],
           [34, 35]],

          [[36, 37],
           [38, 39]]],


         [[[40, 41],
           [42, 43]],

          [[44, 45],
           [46, 47]]]],



        [[[[48, 49],
           [50, 51]],

          [[52, 53],
           [54, 55]]],


         [[[56, 57],
           [58, 59]],

          [[60, 61],
           [62, 63]]]]]])